# 1) Nginx 소스 + 모듈 빌드 (alpine)
FROM alpine:3.18 AS builder

RUN apk add --no-cache \
    gcc libc-dev make pcre-dev openssl-dev zlib-dev curl perl

ENV NGINX_VERSION=1.25.2
ENV NGINX_PURGE_MODULE_VERSION=2.3

WORKDIR /tmp
RUN curl -LO http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
RUN tar -zxvf nginx-${NGINX_VERSION}.tar.gz

RUN curl -LO https://github.com/FRiCKLE/ngx_cache_purge/archive/${NGINX_PURGE_MODULE_VERSION}.tar.gz
RUN tar -zxvf ${NGINX_PURGE_MODULE_VERSION}.tar.gz

WORKDIR /tmp/nginx-${NGINX_VERSION}
RUN ./configure \
    --prefix=/etc/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --sbin-path=/usr/local/sbin/nginx \
    --with-http_stub_status_module \
    --with-http_ssl_module \
    --with-http_gzip_static_module \
    --with-http_realip_module \
    --add-module=/tmp/ngx_cache_purge-${NGINX_PURGE_MODULE_VERSION}

RUN make && make install

# 2) 런타임 이미지
FROM alpine:3.18
RUN apk add --no-cache pcre openssl zlib
RUN addgroup -S nginx && adduser -S -G nginx -h /nonexistent -s /sbin/nologin nginx

COPY --from=builder /etc/nginx /etc/nginx
COPY --from=builder /usr/local/sbin/nginx /usr/local/sbin/nginx

RUN mkdir -p /var/cache/nginx /var/log/nginx && chown -R nginx:nginx /var/cache/nginx /var/log/nginx

# nginx.conf COPY
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
