version: '3.8'
services:
  mysql:
    build:
      context: ../..
      dockerfile: docker/mysql/Dockerfile-mysql
    container_name: mysql_prod
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: freamdb
      MYSQL_USER: fream
      MYSQL_PASSWORD: fream
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql

  redis:
    build:
      context: ../..
      dockerfile: docker/redis/Dockerfile-redis
    container_name: redis_prod
    environment:
      TZ: Asia/Seoul
    ports:
      - "6379:6379"

  zookeeper:
    build:
      context: ../..
      dockerfile: docker/kafka/Dockerfile-zookeeper
    container_name: zookeeper_prod
    environment:
      TZ: Asia/Seoul
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    build:
      context: ../..
      dockerfile: docker/kafka/Dockerfile-kafka
    container_name: kafka_prod
    depends_on:
      - zookeeper
    environment:
      TZ: Asia/Seoul
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_prod:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_prod:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  elasticsearch:
    build:
      context: ../..
      dockerfile: docker/elasticsearch/Dockerfile-elasticsearch
    container_name: es_prod
    environment:
      TZ: Asia/Seoul
      discovery.type: single-node
      xpack.security.enabled: 'false'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data_prod:/usr/share/elasticsearch/data
      - /home/ubuntu/es_logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build:
      context: ../..
      dockerfile: docker/elasticsearch/Dockerfile-kibana
    container_name: kibana_prod
    depends_on:
      - elasticsearch
    environment:
      TZ: Asia/Seoul
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_BASEPATH: /kibana
      SERVER_REWRITEBASEPATH: true
    ports:
      - "5601:5601"

  nginx:
    build:
      context: ../..
      dockerfile: docker/prod/nginx/Dockerfile-nginx-prod
    container_name: nginx_prod
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Asia/Seoul
    depends_on:
      - mysql
      - redis
      - kafka
      - elasticsearch
      - front
      - app
      - certbot
#      - stt_tts
    volumes:
      - letsencrypt_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot

  app:
    image: ghcr.io/junhyeong9812/fream-back:latest
    container_name: spring_boot_app_prod
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
      - kafka
      - elasticsearch
    volumes:
      - /home/ubuntu/fream:/home/ubuntu/fream
  front:
    image: ghcr.io/junhyeong9812/fream-front:latest
    environment:
      TZ: Asia/Seoul
    container_name: fream_front_prod
    depends_on:
      - app  # optional
  # certbot (선택)
  certbot:
    build:
      context: ../..
      dockerfile: docker/prod/nginx/certbot/Dockerfile-certbot
    container_name: certbot_prod
    environment:
      TZ: Asia/Seoul
    volumes:
      - letsencrypt_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM;
      certbot certonly --webroot --webroot-path=/var/www/certbot
      -d www.pinjun.xyz --email pickjog@naver.com --agree-tos --no-eff-email --force-renewal;
      while :; do sleep 12h; certbot renew -q; done"

  cache-cleaner:
    image: alpine:latest
    container_name: cache_cleaner_prod
    depends_on:
      - elasticsearch
      - redis
    volumes:
      - ./scripts:/scripts
    command: >
      sh -c "
      echo '0 2 * * * sh /scripts/clear_caches.sh' > /etc/crontabs/root &&
      crond -f
      "

#  stt_tts:
#    image: fream-stt-tts:latest
#    container_name: stt_tts_prod
#    ports:
#      - "5000:5000"
#    environment:
#      TZ: Asia/Seoul
#    volumes:
#      - stt_tts_models:/app/models
#    restart: unless-stopped
#    depends_on:
#      - app

volumes:
  mysql_data_prod:
  es_data_prod:
  letsencrypt_data:
  certbot_www:
#  stt_tts_models:
