FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=rootpass
ENV MYSQL_DATABASE=freamdb
ENV MYSQL_USER=fream
ENV MYSQL_PASSWORD=fream

EXPOSE 3306

# 만약 my.cnf 필요시:
# COPY my.cnf /etc/mysql/conf.d/my.cnf

CMD ["mysqld"]